export interface Property {
  id: string;
  name: string;
  location: string;
  image: string;
  images: string[];
  status: "Available" | "Reserved" | "Owned";
  capacity: number;
  bedrooms: number;
  bathrooms: number;
  description: string;
  pricePerNight: number;
  amenities: string[];
  address?: string;
  nearestAirport?: string;
  airportDistance?: string;
  airportTime?: string;
  accessInfo?: string;
}

export const properties: Property[] = [
  {
    id: "1",
    name: "Villa Serenity",
    location: "Bali, Indonesia",
    image: "https://images.unsplash.com/photo-1622015663381-d2e05ae91b72?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBtb2Rlcm4lMjB2aWxsYXxlbnwxfHx8fDE3NjQwNDE1MTF8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    images: [
      "https://images.unsplash.com/photo-1622015663381-d2e05ae91b72?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBtb2Rlcm4lMjB2aWxsYXxlbnwxfHx8fDE3NjQwNDE1MTF8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
      "https://images.unsplash.com/photo-1694967832949-09984640b143?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBwb29sJTIwdmlsbGF8ZW58MXx8fHwxNzYzOTY2ODIyfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
      "https://images.unsplash.com/photo-1752769041878-f24e37fd6aea?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtaW5pbWFsaXN0JTIwdmlsbGElMjBpbnRlcmlvcnxlbnwxfHx8fDE3NjQwNDEzNjR8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    ],
    status: "Available",
    capacity: 8,
    bedrooms: 4,
    bathrooms: 3,
    description: "モダンなデザインと自然が調和した、バリ島の高級ヴィラ。広々としたプールとオーシャンビューを備えています。",
    pricePerNight: 85000,
    amenities: ["High-Speed WiFi", "Infinity Pool", "Air Conditioning", "Coffee Machine"],
    address: "Jl. Raya Ubud No.88, Ubud, Gianyar, Bali 80571, Indonesia",
    nearestAirport: "デンパサール・ングラライ国際空港 (DPS)",
    airportDistance: "約35km",
    airportTime: "車で約1時間",
    accessInfo: "空港から専用送迎車で約1時間。またはタクシー・レンタカーでアクセス可能。ウブドの中心部から車で約15分。",
  },
  {
    id: "2",
    name: "Ocean Vista",
    location: "Maldives",
    image: "https://images.unsplash.com/photo-1729808641871-8d8b5ade6bbe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBiZWFjaGZyb250JTIwdmlsbGF8ZW58MXx8fHwxNzY0MDIxMDIzfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    images: [
      "https://images.unsplash.com/photo-1729808641871-8d8b5ade6bbe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBiZWFjaGZyb250JTIwdmlsbGF8ZW58MXx8fHwxNzY0MDIxMDIzfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
      "https://images.unsplash.com/photo-1709744873177-714d7ab0fe02?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx2aWxsYSUyMG9jZWFuJTIwdmlld3xlbnwxfHx8fDE3NjQwNDU2MTF8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    ],
    status: "Available",
    capacity: 6,
    bedrooms: 3,
    bathrooms: 2,
    description: "モルディブの透明な海を一望できる、ビーチフロントの贅沢なヴィラ。",
    pricePerNight: 120000,
    amenities: ["High-Speed WiFi", "Private Beach", "Air Conditioning", "Coffee Machine"],
    address: "North Male Atoll, Maldives",
    nearestAirport: "マレ国際空港 (MLE)",
    airportDistance: "約20km",
    airportTime: "水上飛行機で約30分",
    accessInfo: "マレ国際空港から専用水上飛行機で約30分。またはスピードボートで約45分。リゾート専用の送迎サービスあり。",
  },
  {
    id: "3",
    name: "Mountain Escape",
    location: "Swiss Alps",
    image: "https://images.unsplash.com/photo-1735497947572-0a0301542d4a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBtb3VudGFpbiUyMHZpbGxhfGVufDF8fHx8MTc2NDA0NTYwOXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    images: [
      "https://images.unsplash.com/photo-1735497947572-0a0301542d4a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBtb3VudGFpbiUyMHZpbGxhfGVufDF8fHx8MTc2NDA0NTYwOXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    ],
    status: "Available",
    capacity: 10,
    bedrooms: 5,
    bathrooms: 4,
    description: "スイスアルプスの雄大な景色を望む、モダンな山岳リゾート。",
    pricePerNight: 95000,
    amenities: ["High-Speed WiFi", "Fireplace", "Air Conditioning", "Coffee Machine"],
    address: "Zermatt, Valais, Switzerland",
    nearestAirport: "チューリッヒ空港 (ZRH)",
    airportDistance: "約230km",
    airportTime: "車で約3時間、または電車で約3時間30分",
    accessInfo: "チューリッヒ空港からレンタカーまたは電車で約3時間。ツェルマット駅からケーブルカーで約15分。冬季はスキーリゾートとして最適。",
  },
  {
    id: "4",
    name: "Tropical Paradise",
    location: "Phuket, Thailand",
    image: "https://images.unsplash.com/photo-1728049006343-9ee0187643d5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0cm9waWNhbCUyMHJlc29ydCUyMHZpbGxhfGVufDF8fHx8MTc2Mzk3OTk2MXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    images: [
      "https://images.unsplash.com/photo-1728049006343-9ee0187643d5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0cm9waWNhbCUyMHJlc29ydCUyMHZpbGxhfGVufDF8fHx8MTc2Mzk3OTk2MXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    ],
    status: "Available",
    capacity: 8,
    bedrooms: 4,
    bathrooms: 3,
    description: "プーケットの熱帯雨林に囲まれた、プライベート感あふれるリゾートヴィラ。",
    pricePerNight: 75000,
    amenities: ["High-Speed WiFi", "Infinity Pool", "Air Conditioning", "Coffee Machine"],
    address: "Kamala Beach, Phuket, Thailand",
    nearestAirport: "プーケット国際空港 (HKT)",
    airportDistance: "約25km",
    airportTime: "車で約40分",
    accessInfo: "プーケット国際空港からタクシーまたはレンタカーで約40分。カマラビーチから徒歩5分。ビーチアクセスが便利。",
  },
  {
    id: "5",
    name: "Desert Oasis",
    location: "Dubai, UAE",
    image: "https://images.unsplash.com/photo-1561026555-13539e82532f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkZXNlcnQlMjBsdXh1cnklMjBob3VzZXxlbnwxfHx8fDE3NjQwNDU2MTB8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    images: [
      "https://images.unsplash.com/photo-1561026555-13539e82532f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkZXNlcnQlMjBsdXh1cnklMjBob3VzZXxlbnwxfHx8fDE3NjQwNDU2MTB8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    ],
    status: "Available",
    capacity: 12,
    bedrooms: 6,
    bathrooms: 5,
    description: "ドバイ砂漠の中にある、究極のラグジュアリーヴィラ。",
    pricePerNight: 150000,
    amenities: ["High-Speed WiFi", "Infinity Pool", "Air Conditioning", "Coffee Machine"],
    address: "Al Qudra Road, Dubai, UAE",
    nearestAirport: "ドバイ国際空港 (DXB)",
    airportDistance: "約45km",
    airportTime: "車で約50分",
    accessInfo: "ドバイ国際空港から専用送迎車で約50分。ドバイ中心部から車で約30分。砂漠体験やラクダライドなどのアクティビティが充実。",
  },
  {
    id: "6",
    name: "Contemporary Haven",
    location: "Los Angeles, USA",
    image: "https://images.unsplash.com/photo-1757264119016-7e6b568b810d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb250ZW1wb3JhcnklMjB2aWxsYSUyMHBvb2x8ZW58MXx8fHwxNzY0MDE0ODcwfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    images: [
      "https://images.unsplash.com/photo-1757264119016-7e6b568b810d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb250ZW1wb3JhcnklMjB2aWxsYSUyMHBvb2x8ZW58MXx8fHwxNzY0MDE0ODcwfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    ],
    status: "Available",
    capacity: 10,
    bedrooms: 5,
    bathrooms: 4,
    description: "ロサンゼルスの丘陵地に建つ、コンテンポラリーデザインのヴィラ。",
    pricePerNight: 110000,
    amenities: ["High-Speed WiFi", "Infinity Pool", "Air Conditioning", "Coffee Machine"],
    address: "Beverly Hills, Los Angeles, CA, USA",
    nearestAirport: "ロサンゼルス国際空港 (LAX)",
    airportDistance: "約20km",
    airportTime: "車で約30分",
    accessInfo: "LAX空港からタクシーまたはUberで約30分。ビバリーヒルズの中心部から車で約10分。ハリウッドやサンタモニカビーチへのアクセスも良好。",
  },
  {
    id: "7",
    name: "Zen Retreat",
    location: "Kyoto, Japan",
    image: "https://images.unsplash.com/photo-1544783944-1e6db38b4bfd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxqYXBhbmVzZSUyMG1pbmltYWxpc3QlMjBob3VzZXxlbnwxfHx8fDE3NjQwNDU2MTB8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    images: [
      "https://images.unsplash.com/photo-1544783944-1e6db38b4bfd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxqYXBhbmVzZSUyMG1pbmltYWxpc3QlMjBob3VzZXxlbnwxfHx8fDE3NjQwNDU2MTB8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    ],
    status: "Available",
    capacity: 6,
    bedrooms: 3,
    bathrooms: 2,
    description: "京都の静寂な環境で、日本の伝統美とモダンが融合したヴィラ。",
    pricePerNight: 68000,
    amenities: ["High-Speed WiFi", "Japanese Bath", "Air Conditioning", "Coffee Machine"],
    address: "京都市左京区, 京都府, 日本",
    nearestAirport: "関西国際空港 (KIX)",
    airportDistance: "約100km",
    airportTime: "電車で約1時間30分",
    accessInfo: "関西国際空港からはるかかぜ号で京都駅まで約75分、その後タクシーで約20分。または新大阪から新幹線で京都駅まで約15分。清水寺や金閣寺などの観光地へのアクセスも良好。",
  },
  {
    id: "8",
    name: "Architectural Marvel",
    location: "Barcelona, Spain",
    image: "https://images.unsplash.com/photo-1707648496492-38255a8f1877?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhcmNoaXRlY3R1cmFsJTIwdmlsbGElMjBleHRlcmlvcnxlbnwxfHx8fDE3NjQwNDU2MTF8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    images: [
      "https://images.unsplash.com/photo-1707648496492-38255a8f1877?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhcmNoaXRlY3R1cmFsJTIwdmlsbGElMjBleHRlcmlvcnxlbnwxfHx8fDE3NjQwNDU2MTF8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    ],
    status: "Available",
    capacity: 8,
    bedrooms: 4,
    bathrooms: 3,
    description: "バルセロナの建築美を体現する、芸術的なデザインのヴィラ。",
    pricePerNight: 92000,
    amenities: ["High-Speed WiFi", "Rooftop Terrace", "Air Conditioning", "Coffee Machine"],
    address: "Eixample, Barcelona, Spain",
    nearestAirport: "バルセロナ・エル・プラット空港 (BCN)",
    airportDistance: "約15km",
    airportTime: "車で約25分、または電車で約30分",
    accessInfo: "エル・プラット空港からタクシーまたはAerobusで約25分。サグラダ・ファミリアやランブラス通りなどの観光地から徒歩圏内。",
  },
  {
    id: "9",
    name: "Concrete Haven",
    location: "Tokyo, Japan",
    image: "https://images.unsplash.com/photo-1668536994361-a6aa1fa31050?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBjb25jcmV0ZSUyMGFyY2hpdGVjdHVyZXxlbnwxfHx8fDE3NjM5ODczOTN8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    images: [
      "https://images.unsplash.com/photo-1668536994361-a6aa1fa31050?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBjb25jcmV0ZSUyMGFyY2hpdGVjdHVyZXxlbnwxfHx8fDE3NjM5ODczOTN8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    ],
    status: "Available",
    capacity: 6,
    bedrooms: 3,
    bathrooms: 2,
    description: "東京都心に位置する、ブルータリズム建築の傑作。",
    pricePerNight: 80000,
    amenities: ["High-Speed WiFi", "City View", "Air Conditioning", "Coffee Machine"],
    address: "東京都港区, 日本",
    nearestAirport: "羽田空港 (HND)",
    airportDistance: "約15km",
    airportTime: "電車で約30分",
    accessInfo: "羽田空港から京急線で品川駅まで約15分、その後タクシーで約15分。または成田空港からN'EXで約1時間。六本木や表参道などの都心エリアへのアクセスが便利。",
  },
  {
    id: "10",
    name: "Azure Estate",
    location: "Santorini, Greece",
    image: "https://images.unsplash.com/photo-1694967832949-09984640b143?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBwb29sJTIwdmlsbGF8ZW58MXx8fHwxNzYzOTY2ODIyfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    images: [
      "https://images.unsplash.com/photo-1694967832949-09984640b143?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBwb29sJTIwdmlsbGF8ZW58MXx8fHwxNzYzOTY2ODIyfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    ],
    status: "Available",
    capacity: 10,
    bedrooms: 5,
    bathrooms: 4,
    description: "サントリーニ島のエーゲ海を一望する、白亜のラグジュアリーヴィラ。",
    pricePerNight: 130000,
    amenities: ["High-Speed WiFi", "Infinity Pool", "Air Conditioning", "Coffee Machine"],
    address: "Oia, Santorini, Greece",
    nearestAirport: "サントリーニ空港 (JTR)",
    airportDistance: "約15km",
    airportTime: "車で約25分",
    accessInfo: "サントリーニ空港からタクシーまたはレンタカーで約25分。イアの中心部から徒歩10分。世界一美しい夕日を見るスポットとして有名。",
  },
  {
    id: "11",
    name: "Minimalist Sanctuary",
    location: "Aoshima, Miyazaki",
    image: "https://images.unsplash.com/photo-1752769041878-f24e37fd6aea?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtaW5pbWFsaXN0JTIwdmlsbGElMjBpbnRlcmlvcnxlbnwxfHx8fDE3NjQwNDEzNjR8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    images: [
      "https://images.unsplash.com/photo-1752769041878-f24e37fd6aea?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtaW5pbWFsaXN0JTIwdmlsbGElMjBpbnRlcmlvcnxlbnwxfHx8fDE3NjQwNDEzNjR8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    ],
    status: "Available",
    capacity: 8,
    bedrooms: 4,
    bathrooms: 3,
    description: "宮崎県青島の海岸線に佇む、極限までシンプル化されたデザインのヴィラ。",
    pricePerNight: 72000,
    amenities: ["High-Speed WiFi", "Ocean View", "Air Conditioning", "Coffee Machine"],
    address: "宮崎市青島, 宮崎県, 日本",
    nearestAirport: "宮崎空港 (KMI)",
    airportDistance: "約10km",
    airportTime: "車で約20分",
    accessInfo: "宮崎空港からレンタカーまたはタクシーで約20分。青島ビーチから徒歩3分。宮崎神宮やフェニックス自然動物園へのアクセスも良好。",
  },
  {
    id: "12",
    name: "Brutalist Retreat",
    location: "Oslo, Norway",
    image: "https://images.unsplash.com/photo-1759661030523-6e376ca6a34f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxicnV0YWxpc3QlMjBidWlsZGluZyUyMGV4dGVyaW9yfGVufDF8fHx8MTc2NDA0MTUxMnww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    images: [
      "https://images.unsplash.com/photo-1759661030523-6e376ca6a34f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxicnV0YWxpc3QlMjBidWlsZGluZyUyMGV4dGVyaW9yfGVufDF8fHx8MTc2NDA0MTUxMnww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
    ],
    status: "Available",
    capacity: 4,
    bedrooms: 2,
    bathrooms: 2,
    description: "オスロのフィヨルドを望む、ブルータリズム建築の傑作。",
    pricePerNight: 65000,
    amenities: ["High-Speed WiFi", "Fireplace", "Air Conditioning", "Coffee Machine"],
    address: "Oslo Fjord, Oslo, Norway",
    nearestAirport: "オスロ空港 (OSL)",
    airportDistance: "約50km",
    airportTime: "電車で約25分",
    accessInfo: "オスロ空港から空港急行でオスロ中央駅まで約20分、その後タクシーで約15分。フィヨルドクルーズの出発地点からも近く、ノルウェーの自然を満喫できる。",
  },
];

